version: '2'

services:
#  localstack:
#    container_name: localstack-server
#    image: localstack/localstack
#    ports:
#      - "127.0.0.1:4566:4566"
#      - "127.0.0.1:4510-4559:4510-4559"
  postgres_database:
    container_name: postgres-server
    image: postgres
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    command: -p 5432
    healthcheck:
      test: "exit 0"
  pg_admin:
    container_name: pgadmin4-server
    image: dpage/pgadmin4
    restart: always
    depends_on:
      postgres_database:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
#  keycloak_app:
#    container_name: keycloak_server
#    image: quay.io/keycloak/keycloak:22.0.0
#    command:
#      - start
#    ports:
#      - "8080:8080"
#    environment:
#      KC_DB: postgres
#      KC_DB_URL_HOST: postgres_database
#      KC_DB_URL_DATABASE: learning-security
#      KC_DB_USERNAME: postgres
#      KC_DB_PASSWORD: root
#      KC_DB_SCHEMA: public
#      KEYCLOAK_USER: root
#      KEYCLOAK_PASSWORD: p@ssw0rd
#    depends_on:
#      postgres_database:
#        condition: service_healthy
#    networks:
#      - dev_network
volumes:
  pg_data:
    driver: local